package registry

// RegisterOpenCode registers the OpenCode Free (zen) provider.
func RegisterOpenCode() {
	Register(&RegistryEntry{
		ID:     "opencode",
		Alias:  "oc",
		Name:   "OpenCode Free",
		Format: FormatOpenAI,
		Executor: "opencode",
		BaseURL: "https://opencode.ai/zen/v1",
		ModelsURL: "https://opencode.ai/zen/v1/models",
		AuthType: AuthTypeNoAuth,
		AuthHeader: "Authorization",
		AuthPrefix: "Bearer",
		DefaultContextLength: 200000,
		PassthroughModels: true,
		HasFree: true,
		Models: []RegistryModel{
			{ID: "big-pickle", Name: "Big Pickle", SupportsReasoning: true},
			{ID: "deepseek-v4-flash-free", Name: "DeepSeek V4 Flash Free", SupportsReasoning: true},
			{ID: "minimax-m3-free", Name: "MiniMax M3 Free", ContextLength: 1048576, SupportsVision: true},
			{ID: "minimax-m2.5-free", Name: "MiniMax M2.5 Free", ContextLength: 204800},
			{ID: "ling-2.6-1t-free", Name: "Ling 2.6 Free", ContextLength: 262000},
			{ID: "trinity-large-preview-free", Name: "Trinity Large Preview Free", ContextLength: 131000},
			{ID: "nemotron-3-super-free", Name: "Nemotron 3 Super Free", ContextLength: 1000000},
			{ID: "qwen3.6-plus-free", Name: "Qwen3.6 Plus Free", TargetFormat: FormatClaude, ContextLength: 200000},
		},
	})
}

// RegisterOpenCodeGo registers the OpenCode Go provider.
func RegisterOpenCodeGo() {
	Register(&RegistryEntry{
		ID:     "opencode-go",
		Alias:  "ocgo",
		Name:   "OpenCode Go",
		Format: FormatOpenAI,
		Executor: "opencode",
		BaseURL: "https://opencode.ai/go/v1",
		ModelsURL: "https://opencode.ai/go/v1/models",
		AuthType: AuthTypeAPIKey,
		AuthHeader: "Authorization",
		AuthPrefix: "Bearer",
		DefaultContextLength: 200000,
		PassthroughModels: true,
		Models: []RegistryModel{
			{ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro (Go)", SupportsReasoning: true},
			{ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash (Go)", SupportsReasoning: true},
			{ID: "kimi-k2.6", Name: "Kimi K2.6 (Go)"},
			{ID: "glm-5.1", Name: "GLM 5.1 (Go)"},
			{ID: "minimax-m3", Name: "MiniMax M3 (Go)", ContextLength: 1048576, SupportsVision: true},
		},
	})
}

// RegisterOpenCodeZen registers the OpenCode Zen (API key) provider.
func RegisterOpenCodeZen() {
	Register(&RegistryEntry{
		ID:                 "opencode-zen",
		Alias:              "opencode-zen",
		Format:             FormatOpenAI,
		Executor:           "opencode",
		BaseURL:            "https://opencode.ai/zen/v1",
		ModelsURL:          "https://opencode.ai/zen/v1/models",
		AuthType:           AuthTypeAPIKey,
		AuthHeader:         "Authorization",
		AuthPrefix:         "Bearer",
		DefaultContextLength: 200000,
		PassthroughModels:  true,
		Models: []RegistryModel{
			{ID: "big-pickle", Name: "Big Pickle", SupportsReasoning: true},
			{ID: "gpt-5-nano", Name: "GPT 5 Nano", ContextLength: 400000},
			{ID: "gpt-5", Name: "GPT 5"},
			{ID: "gpt-5-codex", Name: "GPT 5 Codex"},
			{ID: "gpt-5.1", Name: "GPT 5.1"},
			{ID: "gpt-5.1-codex", Name: "GPT 5.1 Codex"},
			{ID: "gpt-5.1-codex-max", Name: "GPT 5.1 Codex Max"},
			{ID: "gpt-5.1-codex-mini", Name: "GPT 5.1 Codex Mini"},
			{ID: "gpt-5.2", Name: "GPT 5.2"},
			{ID: "gpt-5.2-codex", Name: "GPT 5.2 Codex"},
			{ID: "gpt-5.3-codex", Name: "GPT 5.3 Codex"},
			{ID: "gpt-5.3-codex-spark", Name: "GPT 5.3 Codex Spark"},
			{ID: "gpt-5.4", Name: "GPT 5.4"},
			{ID: "gpt-5.4-mini", Name: "GPT 5.4 Mini"},
			{ID: "gpt-5.4-nano", Name: "GPT 5.4 Nano"},
			{ID: "gpt-5.4-pro", Name: "GPT 5.4 Pro"},
			{ID: "gpt-5.5", Name: "GPT 5.5"},
			{ID: "gpt-5.5-pro", Name: "GPT 5.5 Pro"},
			{ID: "claude-haiku-4-5", Name: "Claude Haiku 4.5"},
			{ID: "claude-sonnet-4", Name: "Claude Sonnet 4"},
			{ID: "claude-sonnet-4-5", Name: "Claude Sonnet 4.5"},
			{ID: "claude-sonnet-4-6", Name: "Claude Sonnet 4.6"},
			{ID: "claude-opus-4-1", Name: "Claude Opus 4.1"},
			{ID: "claude-opus-4-5", Name: "Claude Opus 4.5"},
			{ID: "claude-opus-4-6", Name: "Claude Opus 4.6"},
			{ID: "claude-opus-4-7", Name: "Claude Opus 4.7"},
			{ID: "gemini-3-flash", Name: "Gemini 3 Flash"},
			{ID: "gemini-3.1-pro", Name: "Gemini 3.1 Pro"},
			{ID: "gemini-3.5-flash", Name: "Gemini 3.5 Flash"},
			{ID: "grok-build-0.1", Name: "Grok Build 0.1"},
			{ID: "glm-5", Name: "GLM-5"},
			{ID: "glm-5.1", Name: "GLM-5.1"},
			{ID: "minimax-m3", Name: "MiniMax M3", ContextLength: 1048576, SupportsVision: true},
			{ID: "minimax-m2.5", Name: "MiniMax M2.5"},
			{ID: "minimax-m2.7", Name: "MiniMax M2.7"},
			{ID: "kimi-k2.5", Name: "Kimi K2.5"},
			{ID: "kimi-k2.6", Name: "Kimi K2.6"},
			{ID: "qwen3.5-plus", Name: "Qwen3.5 Plus", TargetFormat: FormatClaude},
			{ID: "qwen3.6-plus", Name: "Qwen3.6 Plus", TargetFormat: FormatClaude},
			{ID: "deepseek-v4-flash-free", Name: "DeepSeek V4 Flash Free", SupportsReasoning: true},
			{ID: "minimax-m2.5-free", Name: "MiniMax M2.5 Free", ContextLength: 204800},
			{ID: "nemotron-3-super-free", Name: "Nemotron 3 Super Free", ContextLength: 1000000},
			{ID: "qwen3.6-plus-free", Name: "Qwen3.6 Plus Free", TargetFormat: FormatClaude, ContextLength: 200000},
		},
	})
}
