package registry

// RegisterOpenAI registers the OpenAI provider.
func RegisterOpenAI() {
	Register(&RegistryEntry{
		ID:     "openai",
		Name:   "OpenAI",
		Format: FormatOpenAI,
		Executor: "default",
		BaseURL: "https://api.openai.com/v1",
		ChatPath: "/chat/completions",
		ModelsURL: "https://api.openai.com/v1/models",
		AuthType: AuthTypeAPIKey,
		AuthHeader: "Authorization",
		AuthPrefix: "Bearer ",
		DefaultContextLength: 128000,
		PassthroughModels: true,
		Models: []RegistryModel{
			{ID: "gpt-5.5", Name: "GPT-5.5", ContextLength: 400000, MaxInputTokens: 272000, MaxOutputTokens: 128000, SupportsReasoning: true, SupportsXHighEffort: true},
			{ID: "gpt-5.5-mini", Name: "GPT-5.5 Mini", ContextLength: 128000, SupportsReasoning: true},
			{ID: "gpt-5.4", Name: "GPT-5.4", ContextLength: 128000, SupportsReasoning: true},
			{ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini", ContextLength: 128000},
			{ID: "gpt-5.3-codex", Name: "GPT-5.3 Codex", SupportsReasoning: true, SupportsXHighEffort: true},
			{ID: "gpt-4.1", Name: "GPT-4.1", ContextLength: 1047576, MaxOutputTokens: 32768},
			{ID: "gpt-4.1-mini", Name: "GPT-4.1 Mini", ContextLength: 1047576, MaxOutputTokens: 32768},
			{ID: "gpt-4.1-nano", Name: "GPT-4.1 Nano", ContextLength: 1047576, MaxOutputTokens: 16384},
			{ID: "gpt-4o", Name: "GPT-4o", ContextLength: 128000, SupportsVision: true},
			{ID: "gpt-4o-mini", Name: "GPT-4o Mini", ContextLength: 128000, SupportsVision: true},
			{ID: "gpt-4o-search-preview", Name: "GPT-4o Search Preview", ContextLength: 128000},
			{ID: "gpt-4-turbo", Name: "GPT-4 Turbo", ContextLength: 128000, SupportsVision: true},
			{ID: "gpt-4", Name: "GPT-4", ContextLength: 8192},
			{ID: "gpt-3.5-turbo", Name: "GPT-3.5 Turbo", ContextLength: 16385},
			{ID: "o3", Name: "o3", ContextLength: 200000, SupportsReasoning: true},
			{ID: "o3-mini", Name: "o3 Mini", ContextLength: 200000, SupportsReasoning: true},
			{ID: "o3-pro", Name: "o3 Pro", ContextLength: 200000, SupportsReasoning: true},
			{ID: "o4-mini", Name: "o4 Mini", ContextLength: 200000, SupportsReasoning: true},
			{ID: "chatgpt-4o-latest", Name: "ChatGPT-4o Latest", ContextLength: 128000, SupportsVision: true},
			{ID: "dall-e-3", Name: "DALL-E 3", ContextLength: 4096},
			{ID: "gpt-5.5-xhigh", Name: "GPT-5.5 xHigh", ContextLength: 400000, MaxOutputTokens: 128000, SupportsReasoning: true, SupportsXHighEffort: true},
			{ID: "whisper-1", Name: "Whisper", ContextLength: 0},
			{ID: "tts-1", Name: "TTS 1", ContextLength: 4096},
			{ID: "tts-1-hd", Name: "TTS 1 HD", ContextLength: 4096},
			{ID: "text-embedding-3-large", Name: "Text Embedding 3 Large", ContextLength: 8191},
			{ID: "text-embedding-3-small", Name: "Text Embedding 3 Small", ContextLength: 8191},
			{ID: "text-embedding-ada-002", Name: "Text Embedding Ada 002", ContextLength: 8191},
			{ID: "omni-moderation-latest", Name: "Omni Moderation Latest", ContextLength: 32768},
		},
	})
}
